### ISSUE TITLE
"ValueError" error during step1

### ISSUE THREAD

**Issue by Omer1979** [maiziex/Aquila_stLFR#1]
Hello,
I followed the instructions and got the following error during the 'Cut_phase_blocks' part in step1 :
Traceback (most recent call last):
  File "../Aquila_stLFR/bin/Cut_phaseblock_for_phased_h5_v4.0_highconf_v2.py", line 277, in <module>
    Cut_phaseblock_for_phased_h5(file_name,chr_num,out_file,block_len_use,block_threshold,output_dir,bed_file,phase_block_file,global_track,HC_breakpoint_file,"xin")
  File "../Aquila_stLFR/bin/Cut_phaseblock_for_phased_h5_v4.0_highconf_v2.py", line 189, in Cut_phaseblock_for_phased_h5
    print(np.max(all_cut_block_len))
  File "<__array_function__ internals>", line 6, in amax
  File "/home/omer/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/home/omer/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

However, If I run the code individually for one chromosome at a time (from the same set of input data), I get this error for some chromosomes and not for the others, and for the good ones the step1&step2 can run untill the end with no bugs.

Can you help me or at least explain the difference I get for the some piece of data between chromosomes ?

-- 
-- Omer Murik, Ph.D.Translational Genomics LabMedical Genetics Institute
Shaare Zedek Medical Center
POB 3235
Jerusalem 91031
ISRAEL

**Comment by maiziex** [comment]
Hi Omer,
Do you know the difference (like total coverage, reads/fragment coverage, fragment length?) between your chromosomes? You can try to run Aquila (https://github.com/maiziex/Aquila) instead of Aquila_stLFR for the chromosomes which you had errors. Let me know if you still have errors. 

Best
Maizie

**Comment by omermurik** [comment]
Hi Maizie,

Thanks for your reply.

1. the total coverage, read length, coverage/length was the same between all chromosomes.

2. I tried Aquilla and got the same error.

3. Then I played with the block length parameter value, and only when I lowered it to 20000 (instead of 100K by default) it worked. Can you explain me the nature of that error ?

 

now I have the data i need for all chromosomes, thank you !

Best,

Omer

**Comment by maiziex** [comment]
Hi Omer,
It's great to hear that you also tried the parameter for block length, and it worked. I was about to tell you to try this parameter. It seems like your reads coverage is a little low. For some chromosomes, it didn't return enough with unique mapping coordinates/regions for cutting the phase blocks. 

Best
Maizie
