### ISSUE TITLE
Aquila_stLFR on TELL-Seq read

### ISSUE THREAD

**Issue by LucaBertoli** [maiziex/Aquila_stLFR#3]
Hello,
I was trying to call variants with Aquila_stLFR using TELL-Seq reads (converted in 10x format). I tried to follow the guidelines `https://github.com/BGI-Qingdao/10X2stLFR` and the resulting files have this format:
![immagine](https://user-images.githubusercontent.com/51196235/156765025-2cef81b0-59d5-4a1b-9196-78dcc1b9c089.png)

After the bam processing `(https://github.com/maiziex/Aquila_stLFR/blob/master/src/How_to_get_bam_and_vcf.md)` it gives me an error when trying to run `Aquila_stLFR_step1.py`. 

Is it worth trying to solve it or is it better to use regular Aquila? 

Thank you in advance,
Luca

**Comment by maiziex** [comment]
Hi Luca,
It is better to use regular Aquila for TELL-Seq reads, and I think the problem here is the "#" between the read name and the barcode "BX:Z:XXX". To use Aquila/Aquila_stLFR, there is a "\tab" space between the read name and barcode instead of "#". You can take a look at Supplementary Figure 2 of Aquila_stLFR paper from this link: https://academic.oup.com/bioinformaticsadvances/article/1/1/vbab007/6300508 
I do have some scripts to preprocess TELL-Seq read to prepare the barcoded fastq file. You can email me if you need it.

**Comment by LucaBertoli** [comment]
Hi,
ok, I will switch to regular Aquila and try with it. 

Thanks,
Luca
